services:
    divlooper_elastic.apm.kernel.request:
        class: DivLooper\ElasticAPMBundle\EventListener\RequestListener
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 31 }
        arguments:
            - '@DivLooper\ElasticAPMBundle\ElasticAPMAgent'
    divlooper_elastic.apm.kernel.terminate:
        class: DivLooper\ElasticAPMBundle\EventListener\RequestListener
        tags:
            - { name: kernel.event_listener, event: kernel.terminate, method: onKernelTerminate, priority: -2048 }
        arguments:
            - '@DivLooper\ElasticAPMBundle\ElasticAPMAgent'

    DivLooper\ElasticAPMBundle\ElasticAPMAgent:
        arguments:
            - null
        autowire: true
